### ISSUE TITLE
Feature #1 - User can search for a video meeting their given input criteria.

### ISSUE THREAD

**Issue by jclark-14** [jclark-14/breathe-yoga#1]
## ⚙️ User can search for a video meeting their given input criteria.

> ##### What capability will users have when this feature is merged?

Users will be able to search for yoga videos based on their inputs including:  ability level, yoga type, length and body area of focus (optional).  When the form is submitted, a list of YouTube videos will populate on the page using YouTube API.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user will be able to search for a yoga exercise video matching the goals of their yoga practice. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="575" alt="figma-1" src="https://github.com/user-attachments/assets/1b3cde2e-e11c-424b-ba04-0a6ff098854e">

![IMG_3247](https://github.com/user-attachments/assets/05940a67-cc96-470f-9004-14470dd8f1d3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an HTML skeleton and style it with CSS according to the wireframe.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Create an object to store the users input data when the Search button is pressed.
- [x] Use the created user input object to customize the fetch request to the YouTube API to return videos matching the matching the users input criteria. Max video limit of 5-6 depending on aesthetic. 
- [x] Use the data returned from the YouTube API to create a DOM tree displaying the videos returned on a new view page, according the provided wireframe.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
